### PR TITLE
Pool extends GenericObjectPool

### LINKED ISSUE #1828: Warm the internalPool upon initialization of the JedisPool
### Expected behavior

I'd expect the behavior of creating a GenericConnectionPool to also warm the connection pool based on the configuration of the pool itself (minIdle, etc). This would take place by calling the following method upon initialization of the connection pool:

```
this.internalPool.preparePool();
``` 

This method internally will attempt to ensure that the correct minIdle instances are available for threads to consume and use at the point the pool is first configured. One approach could be to make this optional via a specific pool parameter/argument to say "warmPool: true | false"

### Actual behavior

The GenericObjectPool is created with the correct pool configurations, but the pool is never warmed. The logic within GenericObjectPool itself doesn't warm the pool itself upon creation this is up to the user of the object pool instance to maintain.

### LINKED ISSUE #2197: No way to apply AbandonedConfig in JedisPool
### Expected behavior
Jedis Pool is built over GenericObjectPool from apache commons-pool2. The GenericObjectPool can be configured to detect and remove "abandoned" objects, i.e. objects that have been checked out of the pool but neither used nor returned before the configured removeAbandonedTimeout.

### Actual behavior

There is no way in JedisPool or JedisPoolConfig to configure org.apache.commons.pool2.impl.AbandonedConfig in the underlying jedis pool.

### Steps to reproduce:
We have observed under high load the abandoned connections cause JedisExhaustedPoolException exception and we highly doubt that these are the abandoned connections, as we are releasing all the connections back to pool in a finally block using **jedis.close()** call, evertime we are using it. We get this exception once every 10-12 days in production environment, we are performing around 0.2m operations every minute on a redis setup consisting of 3 servers.

#### Jedis version:
3.1.0

#### Redis version:
redis_version:5.0.2

#### Java version:
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mod

### PR DESCRIPTION
**Pull request by sazzad16**
Resolves #1828 
Closes #2064 
Closes #2054 
Resolves #2197 

By making Pool to extend GenericObjectPool, we can get rid of all the GenericObjectPool specific feature requests. Also, any future GenericObjectPool feature would be readily available in Pool without any sweat.

### CODE REVIEW

File: src/main/java/redis/clients/jedis/JedisSentinelPool.java [hunk 1]
```diff
@@ -184,12 +184,12 @@ public JedisSentinelPool(String masterName, Set<HostAndPort> sentinels,
   }
 
   @Override
-  public void destroy() {
+  public void close() {
```
Comment (gkorland) [inline src/main/java/redis/clients/jedis/JedisSentinelPool.java:187]: @sazzad16 let's keep the destroy method for backward you can just call close() on destory()

File: src/main/java/redis/clients/jedis/util/Pool.java [hunk 2]
```diff
@@ -12,37 +12,15 @@
...
-
-  private final GenericObjectPool<T> internalPool;
+public class Pool<T> extends GenericObjectPool<T> implements Closeable {
 
   public Pool(final GenericObjectPoolConfig<T> poolConfig, PooledObjectFactory<T> factory) {
-    this.internalPool = new GenericObjectPool<>(factory, poolConfig);
-  }
-
-  @Override
-  public void close() {
```
Comment (gkorland) [inline src/main/java/redis/clients/jedis/util/Pool.java:24]: @sazzad16 can we avoid the backward?

File: src/main/java/redis/clients/jedis/util/Pool.java [hunk 3]
```diff
@@ -12,37 +12,20 @@
...
-    this.internalPool = new GenericObjectPool<>(factory, poolConfig);
+    super(factory, poolConfig);
   }
 
   @Override
   public void close() {
     destroy();
   }
 
-  public boolean isClosed() {
```
Comment (gkorland) [inline src/main/java/redis/clients/jedis/util/Pool.java:28]: @sazzad16 what about isClosed and clearInternalPool? Can't we keep them as delegation to avoid breaking changes too?

Comment (sazzad16) [reply src/main/java/redis/clients/jedis/util/Pool.java:28]: @gkorland isClosed is already available in GenericObjectPool.

Comment (sazzad16) [reply src/main/java/redis/clients/jedis/util/Pool.java:28]: @gkorland 

isClosed is already available (in super class, GenericObjectPool).

clearInternalPool is `protected`. So I took the chance of removing it in favor of an available public method `clear()` targeting a major release.

File: src/main/java/redis/clients/jedis/util/Pool.java [hunk 4]
```diff
@@ -57,126 +40,41 @@ public T getResource() {
...
     }
   }
-  
-  /**
-   * Returns the number of instances currently borrowed from this pool.
-   *
-   * @return The number of instances currently borrowed from this pool, -1 if
-   * the pool is inactive.
-   */
-  public int getNumActive() {
```
Comment (gkorland) [inline src/main/java/redis/clients/jedis/util/Pool.java:106]: @sazzad16 should we keep these method to avoid backward issues?

Comment (sazzad16) [reply src/main/java/redis/clients/jedis/util/Pool.java:106]: @gkorland all of these methods are actually available in the super class GenericObjectPool. related tests are available in src/test/java/redis/clients/jedis/tests/JedisPoolTest.java

**Review by gkorland — APPROVED** [review]
