### PR TITLE
Fix parameter types and return types

### LINKED ISSUE #2374: BUG: restore and restoreReplace not using correct native type for the TTL parameter
### Expected behavior

The restore* group of functions use int as the TTL parameter, this should actually be long because the redis restore command sets the TTL as milliseconds NOT seconds.

As per the redis docs: https://redis.io/commands/restore
"If ttl is 0 the key is created without any expire, otherwise the specified expire time (in milliseconds) is set".

### Actual behavior

Integer overflow when passing a large enough TTL as milliseconds

### Steps to reproduce:
```java
String key = "testkey";
int ttl = (int)TimeUnit.DAYS.toSeconds(30); // 30 days as seconds
jedis.set(key, "test-value");
jedis.expire(key, ttl);

// dump record and TTL as milliseconds
byte[] dump = jedis.dump(key);
long pttl = jedis.pttl(key);
jedis.restoreReplace(key, Math.toIntExact(pttl), dump); // results in: ArithmeticException: integer overflow
//jedis.restoreReplace(key, (int)pttl, dump); // unsafe cast results in: JedisDataException: ERR Invalid TTL value, must be >= 0
```

#### Jedis version: 
latest

#### Redis version: 
6.0.9

#### Java version: 
openjdk version "11.0.9.1"

### LINKED ISSUE #2394: Should we keep the parameter types of BinaryJedis PipelineBase stay the same?
e.g. 

`BinaryJedis`
public  List<byte[]> xclaim(byte[] key, byte[] groupname, byte[] consumername, long minIdleTime, long newIdleTime, int retries, boolean force, `byte[][] ids`)

`PipelineBase:`
public Response<List<byte[]>> xclaim(byte[] key, byte[] group, byte[] consumername, long minIdleTime, long newIdleTime, int retries, boolean force, `byte[]... ids`)

`BinaryJedis`
public List<byte[]> xrange(byte[] key, byte[] start, byte[] end, `long count`)

`Jedis`
public List<StreamEntry> xrange(final String key, final StreamEntryID start, final StreamEntryID end, `final int count`)

and BTW
should we return `Response<List<byte[]>>` ？
`redis.clients.jedis.PipelineBase#Response<List<StreamPendingEntry>> xpending(byte[] key, byte[] groupname, byte[] start, byte[] end, int count, byte[] consumername)`

### PR DESCRIPTION
**Pull request by sazzad16**
Resolves #2374 
Resolves #2394

### CODE REVIEW

**Review by dengliming — COMMENTED** [review]
Looks great.

File: src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java [hunk 1]
```diff
@@ -41,11 +41,26 @@
...
   byte[] dump(byte[] key);
 
-  String restore(byte[] key, int ttl, byte[] serializedValue);
+  @Deprecated
+  default String restore(byte[] key, int ttl, byte[] serializedValue) {
+    return restore(key, (long) ttl, serializedValue);
+  }
 
-  String restoreReplace(byte[] key, int ttl, byte[] serializedValue);
+  String restore(byte[] key, long ttl, byte[] serializedValue);
```
Comment (dengliming) [inline src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java]: nice 👍

File: src/main/java/redis/clients/jedis/BinaryShardedJedis.java [hunk 2]
```diff
@@ -1124,14 +1124,15 @@ public Long xtrim(byte[] key, long maxLen, boolean approximateLength) {
   }
 
   @Override
-  public List<byte[]> xpending(byte[] key, byte[] groupname, byte[] start, byte[] end, int count, byte[] consumername) {
+  public List<Object> xpending(byte[] key, byte[] groupname, byte[] start, byte[] end, int count,
```
Comment (dengliming) [inline src/main/java/redis/clients/jedis/BinaryShardedJedis.java:1127]: Any reason to not use `List<byte[]>` here?

Comment (sazzad16) [reply src/main/java/redis/clients/jedis/BinaryShardedJedis.java:1127]: From [Redis doc](https://redis.io/commands/xpending):
```
> XPENDING mystream group55
1) (integer) 1
2) 1526984818136-0
3) 1526984818136-0
4) 1) 1) "consumer-123"
      2) "1"
```
The response can't be represented by `List<byte[]>`.

File: src/main/java/redis/clients/jedis/BinaryClient.java [hunk 3]
```diff
@@ -193,10 +193,15 @@ public void dbSize() {
     sendCommand(DBSIZE);
   }
 
+  @Deprecated
```
Comment (gkorland) [inline src/main/java/redis/clients/jedis/BinaryClient.java:196]: Add deprecated JDoc pointing to the other methods

File: src/main/java/redis/clients/jedis/PipelineBase.java [hunk 4]
```diff
@@ -2088,11 +2088,10 @@
   }
   
   @Override
-  public Response<List<StreamPendingEntry>> xpending(byte[] key, byte[] groupname, byte[] start, byte[] end, int count, byte[] consumername){
+  public Response<List<Object>> xpending(byte[] key, byte[] groupname, byte[] start, byte[] end, int count, byte[] consumername){
```
Comment (gkorland) [inline src/main/java/redis/clients/jedis/PipelineBase.java:2091]: @sazzad16 revert?

**Review by gkorland — CHANGES_REQUESTED** [review]

File: src/main/java/redis/clients/jedis/PipelineBase.java (hunk 4 above)
Comment (sazzad16) [reply src/main/java/redis/clients/jedis/PipelineBase.java]: @gkorland Not exactly but nice catch. Keeping the old version while adding a new method.

File: src/main/java/redis/clients/jedis/BinaryClient.java (hunk 3 above)
Comment (gkorland) [reply src/main/java/redis/clients/jedis/BinaryClient.java:196]: ?

Comment (sazzad16) [reply src/main/java/redis/clients/jedis/BinaryClient.java:199]: @gkorland Ooops!! PTAL again!

**Review by gkorland — APPROVED** [review]

File: src/main/java/redis/clients/jedis/BinaryJedis.java [hunk 5]
```diff
@@ -539,7 +539,7 @@ public Long dbSize() {
    *         2.1.3, Redis &gt;= 2.1.3 will happily update the timeout), or the key does not exist.
    */
   @Override
-  public Long expire(final byte[] key, final int seconds) {
+  public Long expire(final byte[] key, final long seconds) {
```
Comment (walles) [inline src/main/java/redis/clients/jedis/BinaryJedis.java:542]: This is already merged now, but [Duration](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html) might be a better unit for the timeout.

Comment (sazzad16) [reply src/main/java/redis/clients/jedis/BinaryJedis.java:542]: @walles I'm not sure if you noticed, this not related to socket timeout. This is actually [EXPIRE](https://redis.io/commands/expire) command.

Still, this can be considered. But let's rebuild Jedis first :)
