### PR TITLE
Fix flaky test JedisPoolTest.testCloseConnectionOnMakeObject

### LINKED ISSUE #4135: Fix flaky test JedisPoolTest.testCloseConnectionOnMakeObject
The test JedisPoolTest.testCloseConnectionOnMakeObject occasionally fails with the following error:

    `JedisPoolTest.testCloseConnectionOnMakeObject:403 expected:<4> but was:<5>`

**Root Cause:**
The assertion is based on the output of getClientCount(jedis.clientList()), which is called immediately after closing a connection. However, Redis may take a short time to remove the closed connection from the client list, leading to a transient count mismatch and a flaky test result.

**Example stack trace:**
```
Error:  redis.clients.jedis.JedisPoolTest.testCloseConnectionOnMakeObject -- Time elapsed: 0.006 s <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<5>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at redis.clients.jedis.JedisPoolTest.testCloseConnectionOnMakeObject(JedisPoolTest.java:403)
```

### PR DESCRIPTION
**Pull request by thachlp**
The test JedisPoolTest.testCloseConnectionOnMakeObject occasionally fails with the following error:

    `JedisPoolTest.testCloseConnectionOnMakeObject:403 expected:<4> but was:<5>`

**Root Cause:**
The assertion is based on the output of getClientCount(jedis.clientList()), which is called immediately after closing a connection. However, Redis may take a short time to remove the closed connection from the client list, leading to a transient count mismatch and a flaky test result.

**Example stack trace:**
```
Error:  redis.clients.jedis.JedisPoolTest.testCloseConnectionOnMakeObject -- Time elapsed: 0.006 s <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<5>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at redis.clients.jedis.JedisPoolTest.testCloseConnectionOnMakeObject(JedisPoolTest.java:403)
```
	
closes #4135

### CODE REVIEW

File: src/test/java/redis/clients/jedis/JedisPoolTest.java [hunk 1]
```diff
@@ -395,12 +395,28 @@ public void testCloseConnectionOnMakeObject() {
     try (JedisPool pool = new JedisPool(new JedisPoolConfig(), endpointStandalone0.getHost(),
         endpointStandalone0.getPort(), 2000, "wrong pass");
         Jedis jedis = new Jedis(endpointStandalone0.getURIBuilder().defaultCredentials().build())) {
-      int currentClientCount = getClientCount(jedis.clientList());
+      int initialClientCount = getClientCount(jedis.clientList());
+      boolean clientCountStabilized = false;
```
Comment (ggivo) [inline src/test/java/redis/clients/jedis/JedisPoolTest.java:399]:
```suggestion
int currentClientCount = getClientCount(jedis.clientList());
```

File: src/test/java/redis/clients/jedis/JedisPoolTest.java [hunk 2]
```diff
@@ -395,12 +395,28 @@ public void testCloseConnectionOnMakeObject() {
...
+            break;
+          }
+          try {
+            Thread.sleep(100);
+          } catch (InterruptedException ex) {
+            Thread.currentThread().interrupt();
+          }
+        }
+        assertEquals(initialClientCount, getClientCount(jedis.clientList()));
+        assertTrue("Client count did not stabilize within the timeout.", clientCountStabilized);
```
Comment (ggivo) [inline src/test/java/redis/clients/jedis/JedisPoolTest.java:419]:
```suggestion
      // wait for the redis server to close the connection
      await().pollDelay(Duration.ofMillis(10)).atMost(50, MILLISECONDS)
          .until(() -> getClientCount(jedis.clientList()) == currentClientCount);
      assertEquals(currentClientCount, getClientCount(jedis.clientList()));
```

Comment (ggivo) [reply src/test/java/redis/clients/jedis/JedisPoolTest.java:419]: Need also
`import static org.awaitility.Awaitility.await;`

Same test exists and need to be  fixed in ACLJedisPoolTest https://github.com/redis/jedis/blob/3f8e5d29347681b0e6a82a18874dcb615fe18595/src/test/java/redis/clients/jedis/ACLJedisPoolTest.java#L265

**Review by ggivo — CHANGES_REQUESTED** [review]

**Comment by ggivo** [comment]
@thachlp 
Thanks for looking into the issue! 
I think using Awaitility would simplify things.

**Review by thachlp — COMMENTED** [review]
Thank @thachlp for helping me update the description.
Btw, I tried to run format and validate and it was successful, but it still fail on check-format job.
What do I miss? 🙇

File: src/test/java/redis/clients/jedis/JedisPoolTest.java (hunk 2 above)
Comment (thachlp) [reply src/test/java/redis/clients/jedis/JedisPoolTest.java]: Updated

File: src/test/java/redis/clients/jedis/JedisPoolTest.java (hunk 1 above)
Comment (thachlp) [reply src/test/java/redis/clients/jedis/JedisPoolTest.java]: Nice, thanks 🙇

**Comment by ggivo** [comment]
> Thank @thachlp for helping me update the description. Btw, I tried to run format and validate and it was successful, but it still fail on check-format job. What do I miss? 🙇

Since code formatting was not enforced there are lots of discrepancies in the code. We are currently experimenting with how to enforce it. [Java Format Check] is optional currently and serves as a hint to reviewers that the code is not properly formatted. You can discard it for now. In case formatting the whole file introduces lots of additional formatting changes and makes the review harder my advice is to format only the modified code. Code formatting rules can be found `hbase-formatter.xml.`

PS: `mvn formatter:format` will reformat only sources described here
https://github.com/ggivo/jedis/blob/a4d2b8d062a3ecb878750f83abe0439f01100739/pom.xml#L329-L329

File: src/test/java/redis/clients/jedis/ACLJedisPoolTest.java [hunk 3]
```diff
@@ -264,12 +267,9 @@ public void testCloseConnectionOnMakeObject() {
         Jedis jedis = new Jedis(endpointWithDefaultUser.getURIBuilder()
             .credentials("", endpointWithDefaultUser.getPassword()).build())) {
       int currentClientCount = getClientCount(jedis.clientList());
-      try {
-        pool.getResource();
-        fail("Should throw exception as password is incorrect.");
-      } catch (Exception e) {
```
Comment (ggivo) [inline src/test/java/redis/clients/jedis/ACLJedisPoolTest.java:270]: In order test to be valid we should still perform request for connection
We need to keep try/catch  pool.getResource();
```
      try {
        pool.getResource();
        fail("Should throw exception as password is incorrect.");
      } catch (Exception e) {
            await().pollDelay(Duration.ofMillis(10)).atMost(50, MILLISECONDS)
          .until(() -> getClientCount(jedis.clientList()) == currentClientCount);
      assertEquals(currentClientCount, getClientCount(jedis.clientList()));
      }
```

File: src/test/java/redis/clients/jedis/JedisPoolTest.java [hunk 4]
```diff
@@ -396,12 +399,9 @@ public void testCloseConnectionOnMakeObject() {
         endpointStandalone0.getPort(), 2000, "wrong pass");
         Jedis jedis = new Jedis(endpointStandalone0.getURIBuilder().defaultCredentials().build())) {
       int currentClientCount = getClientCount(jedis.clientList());
-      try {
-        pool.getResource();
-        fail("Should throw exception as password is incorrect.");
-      } catch (Exception e) {
-        assertEquals(currentClientCount, getClientCount(jedis.clientList()));
-      }
```
Comment (ggivo) [inline src/test/java/redis/clients/jedis/JedisPoolTest.java:404]: In order test to be valid we should still perform request for connection
We need to keep try/catch  pool.getResource();
```
      try {
        pool.getResource();
        fail("Should throw exception as password is incorrect.");
      } catch (Exception e) {
            await().pollDelay(Duration.ofMillis(10)).atMost(50, MILLISECONDS)
          .until(() -> getClientCount(jedis.clientList()) == currentClientCount);
      assertEquals(currentClientCount, getClientCount(jedis.clientList()));
      }
```

**Review by ggivo — CHANGES_REQUESTED** [review]

File: src/test/java/redis/clients/jedis/ACLJedisPoolTest.java (hunk 3 above)
Comment (thachlp) [reply src/test/java/redis/clients/jedis/ACLJedisPoolTest.java]: My mistake, thanks 😃

File: src/test/java/redis/clients/jedis/JedisPoolTest.java (hunk 4 above)
Comment (thachlp) [reply src/test/java/redis/clients/jedis/JedisPoolTest.java]: Done
