### PR TITLE
Fix for bug #4003. Better message instead of ArrayIndexOutOfBoundsExce

### LINKED ISSUE #4003: Fix JedisURIHelper.getPassword throwing ArrayIndexOutOfBoundsException for username-only URIs
Authentication details can be provided in the URI in the form of a username and password.
Redis URIs may contain authentication details that effectively lead to **usernames with passwords**, **password-only**, or **no authentication**.

Examples : 
 - Username and Password: `redis://username:password@host:port`
 - Password-only: `redis://:password@host:port `
 - No Authentication:  `redis://host:port `
 - Empty password: `redis://username:@host:port `
 
Using JedisURIHelper with a URI having only a username is considered invalid and should throw `IllegalArgumentException`.
 - Username-only:  `redis://username@host:port`

### Expected behavior

JedisURIHelper.getPassword throws `IllegalArgumentException`  when there is only a username and no password in the URI.

### Actual behavior

JedisURIHelper.getPassword does throw an exception `ArrayIndexOutOfBoundsException` when there is only a username and no password in the URI.

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at redis.clients.jedis.util.JedisURIHelper.getPassword(JedisURIHelper.java:36)
```

### Steps to reproduce:

```java
URI redisProperUri = URI.create("redis://user@redisHost.redisDomain");
JedisURIHelper.getPassword(redisProperUri); 
```

### PR DESCRIPTION
**Pull request by smadasu**
Fix for bug #4003. Better message instead of ArrayIndexOutOfBoundsException

Closes #4003.

### CODE REVIEW

File: src/test/java/redis/clients/jedis/util/JedisURIHelperTest.java [hunk 1]
```diff
@@ -1,15 +1,14 @@
...
-import static org.junit.Assert.assertEquals;
-import static org.junit.Assert.assertFalse;
-import static org.junit.Assert.assertNull;
-
 import java.net.URI;
 import java.net.URISyntaxException;
 import org.junit.Test;
+import org.junit.rules.ExpectedException;
 import redis.clients.jedis.RedisProtocol;
+import redis.clients.jedis.exceptions.JedisException;
```
Comment (ggivo) [inline src/test/java/redis/clients/jedis/util/JedisURIHelperTest.java:11]:
```suggestion
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.emptyString;
```
Because of IllegalArgumentException + new test for emptyPassword

File: src/test/java/redis/clients/jedis/util/JedisURIHelperTest.java [hunk 2]
```diff
@@ -73,4 +72,13 @@ public void shouldGetProtocolFromDefinition() {
...
   }
+
+  @Test
+  public void shouldReturnNullIfURIDoesNotHavePassword() throws URISyntaxException {
+    URI uri = new URI("redis://user@host:9000/0");
+    JedisException jedisException = assertThrows(JedisException.class, () -> {
+      getPassword(uri);
+    });
+    assertEquals(jedisException.getMessage(), "AUTH error. Password not provided in uri");
+  }
```
Comment (ggivo) [inline src/test/java/redis/clients/jedis/util/JedisURIHelperTest.java:83]:
```suggestion
  @Test
  public void shouldReturnEmptyPassword() {
    // ensure we can provide an empty password for default user
    assertThat( JedisURIHelper.getPassword(URI.create("redis://:@host:9000/0")),  emptyString());
  }

  @Test
  public void shouldThrowIfNoPasswordInURI() throws URISyntaxException {
    // ensure we throw if user is provided but password is missing in URI
    URI uri = new URI("redis://user@host:9000/0");
    IllegalArgumentException jedisException = assertThrows(IllegalArgumentException.class, () -> {
      getPassword(uri);
    });
    assertEquals(jedisException.getMessage(), "Password not provided in the URI");
  }
```
Update the test to use IllegalArgumentException

**Review by ggivo — CHANGES_REQUESTED** [review]
Hi, @smadasu 

Thanks for spending time on this issue.
It looks good to me. I have posted some suggestions. 
I think IllegalArgumentException  is a better fit and more cossisstent with rest of the JedisURIHelper . 

Thanks again!

File: src/test/java/redis/clients/jedis/util/JedisURIHelperTest.java (hunk 2 above)
Comment (smadasu) [reply src/test/java/redis/clients/jedis/util/JedisURIHelperTest.java:83]: Sounds good. Let me push review suggestions

**Review by ggivo — APPROVED** [review]
LGTM!

**Comment by ggivo** [comment]
@smadasu 
Merged.  Thanks again for your contribution!
