### PR TITLE
Avoid QUIT for broken connections

### LINKED ISSUE #2108: Pooled Connections shouldn't be closed if they have socket timeouts
The following line can throw a SocketTimeoutException and in that case, the connection is marked as broken.
https://github.com/xetorthio/jedis/blob/6126d30efccb8921dcf9a03776299a504e022a3e/src/main/java/redis/clients/jedis/Connection.java#L126

Then when the close() method is called (the intention is to add the connection back to the pool), then the broken client is eventually closed:
https://github.com/xetorthio/jedis/blob/6126d30efccb8921dcf9a03776299a504e022a3e/src/main/java/redis/clients/jedis/Jedis.java#L3458

The above call will end up in the invalidateObject() method in the commons-pool2:
https://github.com/apache/commons-pool/blob/f4455dcb8afaf9ae7054589110f1082a7a8a282c/src/main/java/org/apache/commons/pool2/impl/GenericObjectPool.java#L607

which eventually will call:
https://github.com/xetorthio/jedis/blob/6126d30efccb8921dcf9a03776299a504e022a3e/src/main/java/redis/clients/jedis/JedisFactory.java#L94

This is the cause of issue https://github.com/xetorthio/jedis/issues/2105, where the guys see a large number of new connections. I was able to reproduce it by lowering the socket timeout.

### PR DESCRIPTION
**Pull request by sazzad16**
Note: Found it hard to write proper test codes. We may need to mock for this purpose.

### CODE REVIEW

**Comment by yangbodong22011** [comment]
Hi, @sazzad16, the code look good to me, but i don't think it will solve #2108 #2105

Under current jedis netWork protocol, if a operation timeouted, will set `borken = true`, then the socket will be closed. The reason is the socket may be return data after sometime, this may cause next operation get error response.

About this issue, i think the only way to avoid close connection is increase `soTimeout`.

**Comment by sazzad16** [comment]
@yangbodong22011 The object will be returned to the pool as a broken resource. The pool will remove it and never use it again. If necessarily, the pool will create a new resource which will have a new socket. Do you think it will still be a problem?

**Comment by yangbodong22011** [comment]
> @yangbodong22011 The object will be returned to the pool as a broken resource. The pool will remove it and never use it again. If necessarily, the pool will create a new resource which will have a new socket. Do you think it will still be a problem?

This is the current logic, and it is correct. but `create a new resource` will cause https://github.com/redis/jedis/issues/2105#issuecomment-557901749 . 
One way to avoid connection broken is to avoid timeout, that is, increase `soTimeout`.

**Comment by sazzad16** [comment]
> but `create a new resource` will cause https://github.com/redis/jedis/issues/2105#issuecomment-557901749 . 
> One way to avoid connection broken is to avoid timeout, that is, increase `soTimeout`.

The goal of this PR is not to avoid creating new connections and solve #2105. The goal here is to avoid executing a Redis command (QUIT) with a connection which is already broken while trying to execute some other command.

If you are not convinced that this will resolve #2108, we can still keep the issue open and move forward with this PR.

File: Makefile [hunk 1]
```diff
@@ -338,6 +351,7 @@ stop:
 	kill `cat /tmp/redis_cluster_node5.pid` || true
 	kill `cat /tmp/redis_uds.pid` || true
 	kill `cat /tmp/stunnel.pid` || true
+	# kill `cat /tmp/redis_unavailable.pid` || true
```
Comment (mina-asham) [inline Makefile:354]: Need to uncomment

File: src/main/java/redis/clients/jedis/BinaryShardedJedis.java [hunk 2]
```diff
@@ -19,6 +21,8 @@
 public class BinaryShardedJedis extends Sharded<Jedis, JedisShardInfo> implements
     BinaryJedisCommands {
 
+  private final Logger logger = LoggerFactory.getLogger(getClass());
```
Comment (mina-asham) [inline src/main/java/redis/clients/jedis/BinaryShardedJedis.java:24]: Loggers should be `static` otherwise they could introduce performance issues. (Applies in a few other places too)

File: src/main/java/redis/clients/jedis/BinaryShardedJedis.java [hunk 3]
```diff
@@ -41,14 +45,19 @@ public void disconnect() {
...
       if (jedis.isConnected()) {
         try {
-          jedis.quit();
+          // need a proper test, probably with mock
+          if (!jedis.isBroken()) {
+            jedis.quit();
+          }
         } catch (JedisConnectionException e) {
           // ignore the exception node, so that all other normal nodes can release all connections.
+          logger.error("Error while QUIT", e);
```
Comment (mina-asham) [inline src/main/java/redis/clients/jedis/BinaryShardedJedis.java:54]: Can we reduce this to WARN or INFO, lots of people will have alarms on ERRORs, so if we start adding these it might be tempting for people to turn off the logger completely and they might lose some good information here (Applies in a few other places too)

File: src/main/java/redis/clients/jedis/BinaryShardedJedis.java [hunk 4]
```diff
@@ -41,14 +45,19 @@ public void disconnect() {
...
         }
         try {
           jedis.disconnect();
```
Comment (mina-asham) [inline src/main/java/redis/clients/jedis/BinaryShardedJedis.java:57]: Can we actually disconnect in a broken state?

**Review by mina-asham — CHANGES_REQUESTED** [review]

File: Makefile (hunk 1 above)
Comment (sazzad16) [reply Makefile:354]: NO.
This redis instance is supposed to be shutdown at `UnavailableConnectionTest`.
I've added this line just to trace the instances. I'm not sure whether we should though.

File: src/main/java/redis/clients/jedis/BinaryShardedJedis.java (hunk 4 above)
Comment (sazzad16) [reply src/main/java/redis/clients/jedis/BinaryShardedJedis.java:57]: Yes, we can. It actually flushes socket stream and closes socket.

File: Makefile (hunk 1 above)
Comment (mina-asham) [reply Makefile:354]: But what if the test fails that will leave a rogue running instance, I think we should try and kill it here since this happens *after* running all the tests and would pass still if the process is already dead because of `|| true` bit

File: src/main/java/redis/clients/jedis/BinaryShardedJedis.java (hunk 4 above)
Comment (mina-asham) [reply src/main/java/redis/clients/jedis/BinaryShardedJedis.java:57]: But wouldn't flush fail in that case? (I guess the `finally` in `Connection.disconnet` still makes sure the socket is closed if possible so it might be fine), if your test and manual run works fine then that's okay then.

Comment (sazzad16) [reply src/main/java/redis/clients/jedis/BinaryShardedJedis.java:57]: Jedis is disconnecting broken connections since ages. It is yet to be pin-pointed as an issue :laughing:

File: src/main/java/redis/clients/jedis/JedisFactory.java [hunk 5]
```diff
@@ -129,12 +134,17 @@ public void destroyObject(PooledObject<Jedis> pooledJedis) throws Exception {
...
     if (jedis.isConnected()) {
       try {
-        try {
+        // need a proper test, probably with mock
+        if (!jedis.isBroken()) {
           jedis.quit();
-        } catch (Exception e) {
         }
+      } catch (Exception e) {
+        logger.error("Error while QUIT", e);
```
Comment (sazzad16) [inline src/main/java/redis/clients/jedis/JedisFactory.java:142]:
```suggestion
        logger.warn("Error while QUIT", e);
```

File: src/main/java/redis/clients/jedis/JedisFactory.java [hunk 6]
```diff
@@ -129,12 +134,17 @@ public void destroyObject(PooledObject<Jedis> pooledJedis) throws Exception {
...
+      }
+      try {
         jedis.disconnect();
       } catch (Exception e) {
+        logger.error("Error while disconnect", e);
```
Comment (sazzad16) [inline src/main/java/redis/clients/jedis/JedisFactory.java:147]:
```suggestion
        logger.warn("Error while disconnect", e);
```

File: src/main/java/redis/clients/jedis/ShardedJedisPool.java [hunk 7]
```diff
@@ -79,14 +85,17 @@ public void destroyObject(PooledObject<ShardedJedis> pooledShardedJedis) throws
...
           try {
-            try {
+            // need a proper test, probably with mock
+            if (!jedis.isBroken()) {
               jedis.quit();
-            } catch (Exception e) {
-
             }
+          } catch (Exception e) {
+            logger.error("Error while QUIT", e);
```
Comment (sazzad16) [inline src/main/java/redis/clients/jedis/ShardedJedisPool.java:93]:
```suggestion
            logger.warn("Error while QUIT", e);
```

File: src/main/java/redis/clients/jedis/ShardedJedisPool.java [hunk 8]
```diff
@@ -79,14 +85,17 @@ public void destroyObject(PooledObject<ShardedJedis> pooledShardedJedis) throws
...
+          }
+          try {
             jedis.disconnect();
           } catch (Exception e) {
-
+            logger.error("Error while disconnect", e);
```
Comment (sazzad16) [inline src/main/java/redis/clients/jedis/ShardedJedisPool.java:98]:
```suggestion
            logger.warn("Error while disconnect", e);
```

File: src/main/java/redis/clients/jedis/BinaryShardedJedis.java (hunk 4 above)
Comment (mina-asham) [reply src/main/java/redis/clients/jedis/BinaryShardedJedis.java:57]: I yield to empirical evidence then 😅

File: src/main/java/redis/clients/jedis/JedisFactory.java [hunk 9]
```diff
@@ -19,6 +21,9 @@
  * PoolableObjectFactory custom impl.
  */
 class JedisFactory implements PooledObjectFactory<Jedis> {
+
+  private final Logger logger = LoggerFactory.getLogger(getClass());
```
Comment (mina-asham) [inline src/main/java/redis/clients/jedis/JedisFactory.java:25]: Missed one

File: Makefile (hunk 1 above)
Comment (sazzad16) [reply Makefile:354]: AFAICR, I commented it because it failed.

File: src/main/java/redis/clients/jedis/JedisFactory.java (hunk 9 above)
Comment (sazzad16) [inline src/main/java/redis/clients/jedis/JedisFactory.java:25]:
```suggestion
  private static final Logger logger = LoggerFactory.getLogger(JedisFactory.class);
```

File: Makefile (hunk 1 above)
Comment (mina-asham) [reply Makefile:354]: You're right, Redis deletes the pid file on exit, how about this to check if the file exists first:
```suggestion
	[ -f /tmp/redis_unavailable.pid ] && kill `cat /tmp/redis_unavailable.pid` || true
```

**Review by mina-asham — APPROVED** [review]
